### ISSUE TITLE
  token manager GetToken() exception when apikey could not be found

### ISSUE THREAD

**Issue by mdeuser** [IBM/go-sdk-core#11]
When an invalid apikey is used to create a token manager, subsequent calls to GetToken() result in a nil pointer dereference

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x82de4c]

goroutine 58 [running]:
github.com/IBM/go-sdk-core/core.(*TokenManager).GetToken(0xc000278060, 0x1f, 0xc000498ad0, 0x1, 0x1)
        C:/Whisk/CloudObjectStore/bluewhisk-cos-event-provider/pkg/mod/github.com/!i!b!m/go-sdk-core@v0.3.0/core/token_manager.go:102 +0x7c
```

This issue is in line https://github.com/IBM/go-sdk-core/blob/6c0923c26661bddf6f48f4ad1076727a87d2e0c2/core/token_manager.go#L102

and also https://github.com/IBM/go-sdk-core/blob/6c0923c26661bddf6f48f4ad1076727a87d2e0c2/core/token_manager.go#L112

When `tm.requestToken()` fails, the returned `*TokenInfo` is nil; however, it is dereferenced in the above lines, causing the exception.

A proposed fix for this issue
```
                ...
		tokenInfo, err := tm.requestToken()
                if err != nil {
                        return "", err
                }
		tm.saveTokenInfo(tokenInfo)
                return tm.tokenInfo.AccessToken, err
                ...
```

**Comment by Alwandy** [comment]
Not even for invalid, if the connection is blocked by firewall / proxy / antivirus also..

**Comment by dubee** [comment]
@ehdsouza, any updates on this one?

**Comment by ehdsouza** [comment]
An upcoming PR with ICP4D support would have authentication changes which would be released this week.
