### ISSUE TITLE
[Question] Why a lot of packages?

### ISSUE THREAD

**Issue by mirusky-enube** [IBM/go-sdk-core#117]
Please I just want to understand why we have an package for auth, another for k8s operators, another one to billing, this one and a lot of others. 

Why don't just create a [go monorepo](https://github.com/golang-standards/project-layout) ? And organize things there ?

**Comment by padamstx** [comment]
In general SDKs for IBM Cloud services are organized around the service categories found here: https://cloud.ibm.com/docs?tab=api-docs
For example, for the "Platform" category, we have the following SDKs 
* [Platform Services Go SDK](https://github.com/IBM/platform-services-go-sdk)
* [Platform Services Java SDK](https://github.com/IBM/platform-services-java-sdk)
* [Platform Services Node.js SDK](https://github.com/IBM/platform-services-node-sdk)
* [Platform Services Python SDK](https://github.com/IBM/platform-services-python-sdk)
There are other sets of SDK projects for some of the other service categories as well.  Our goal is to eventually provide SDKs for all service categories.

For an SDK that supports a particular language (e.g. the Platform Services Go SDK mentioned above), that SDK project will depend on the "core" library for that language (e.g. Go SDKs depend on the go-sdk-core library, Java SDKs depend on the java-sdk-core library, and so on).   The "core" library for a particular language provides a set of common  functionality (REST API processing, authentication, etc.) that is used by the generated SDK code packaged inside each SDK project.

**Comment by mirusky-enube** [comment]
Alright, but think as a developer when you download some SDK you expect that particular SDK provide everything you need. So you don't want to search every piece of code while you writing the project, you just want to download and use.
