### ISSUE TITLE
Token expiration check should provide some time for token usage

### ISSUE THREAD

**Issue by mdeuser** [IBM/go-sdk-core#14]
Currently, the isTokenExpired code will return `false` even when the token only has 1 ms left until expiration.
```
func (tm *IAMTokenManager) isTokenExpired() bool {
	if tm.timeForNewToken == 0 {
		return true
	}

	currentTime := GetCurrentTime()
	return tm.timeForNewToken < currentTime
}
```
This means that the consumer of the token will probably get a 401 response to any request using this "1 ms" token.

This issue is proposing that some additional margin be added to the `isTokenExpired` function so that the returned token has some minimum time that the token is guaranteed to be valid.

I'm not exact sure what this minimum might be though... Maybe when the token is about 80% close to the expiration time, the token is considered expired.  Another thought would be for the TokenManager to take another parameter that the user/consumer would dictate the minimum time (in ms) the returned token should be guaranteed to be valid.

**Comment by mdeuser** [comment]
I missed this following bit of code
https://github.com/IBM/go-sdk-core/blob/e68c8f8b929ce0e41ee72623016ea2663af50d0c/core/iam_token_manager.go#L174
which does implement an 80% rule (i.e. considers token expired when 80% of the expiration time has elapsed)

**Comment by ehdsouza** [comment]
@mdeuser yes we do jave the `80%` fraction. Right now all our SDKs support it. What do you suggest?

**Comment by mdeuser** [comment]
@ehdsouza - thank you for the response!  now that i better understand the 80% implementation, i think that should be ok.. at least for our current use.

**Comment by mdeuser** [comment]
hi @ehdsouza - the logic 
```
fractionOfTimeToLive := 0.8
timeForNewToken := expireTime - (timeToLive * int64(1.0-fractionOfTimeToLive))
```
won't actually calculate 80% of the expiration time.  the int64 logic will truncate the integer so that the expiration time is actually 100% of the original expiration time.  Does that sound right to you?

https://play.golang.org/p/U0cyTlz40ko

**Comment by dubee** [comment]
What actually happens here is `timeForNewToken := expireTime - (timeToLive * 0)`, so `timeForNewToken` ends up equaling `expireTime`. This is because `int64(1.0-fractionOfTimeToLive)` is rounded to 0 when the integer cast occurs.

**Comment by dubee** [comment]
I would suggest `timeForNewToken := int64(float64(expireTime) - (float64(timeToLive) * (1.0-fractionOfTimeToLive)))` instead. 

Is `timeToLive` always an hour? If not, the equation does not work very well for small `timeToLive`  values.

**Comment by dubee** [comment]
@ehdsouza, any updates on this one?

**Comment by ehdsouza** [comment]
Hi @dubee,

Thanks for pointing it out. Would you like to submit a PR with a proposed fix?

**Comment by dubee** [comment]
@ehdsouza, I opened a PR if you can take please take a look.
