### ISSUE TITLE
IAMAuthenticator using APIKEY results in panic - v5.9.0

### ISSUE THREAD

**Issue by saikumar1607** [IBM/go-sdk-core#155]
We are using go-core-sdk as a dependency to our hand-written SDK.  In our SDK, all the API requests/response are managed using the go-core-sdk methods

sample program
```go

authenticator, err := core.NewIamAuthenticatorBuilder().
        SetApiKey(apikey).
        SetURL(iamURL).
	Build()

serviceOptions := &core.ServiceOptions{
	URL:           "https://us-south.apprapp.cloud.ibm.com",
	Authenticator: authenticator,
}

var baseService = *core.BaseService
baseService, _ = core.NewBaseService(serviceOptions)
request, err := builder.Build()

var rawResponse map[string]json.RawMessage
response, _ := baseService.Request(request, &rawResponse)
```

Until v5.8.2 everything worked fine. When we upgrade to v5.9.0+ our API requests codebase gets panicked with error
`Exactly one of ApiKey or RefreshToken must be specified.`

#### USE CASE

In our handwritten SDKs, we make repeated API calls to same endpoint at regular intervals.
The authenticator & serviceOptions are initialised once.
And they are passed to 
```go
var baseService = *core.BaseService
baseService, _ = core.NewBaseService(serviceOptions)
request, err := builder.Build()

var rawResponse map[string]json.RawMessage
response, _ := baseService.Request(request, &rawResponse)
```
for every API calls we make.

### Result

First API call made gets succeeded, all the following API calls results in panic with error `Exactly one of ApiKey or RefreshToken must be specified.`

This is because in **first API** call refresh_token will be empty

<img width="300" alt="Screenshot 2022-01-31 at 6 37 21 PM" src="https://user-images.githubusercontent.com/75735146/152036823-4e557cb3-d028-4775-b648-3985a695a44c.png">

For the **following API call** refresh_token has value `not_supported`
<img width="300" alt="Screenshot 2022-01-31 at 6 37 21 PM" src="https://user-images.githubusercontent.com/75735146/152037078-c248d1bf-e0ca-4257-aa47-c3b60a66de82.png">

which results in panic and we are not able to use version v5.9.0+ to support our use-case

**Comment by padamstx** [comment]
The NewBaseService() function will (in addition to constructing a new BaseService instance) invoke the authenticator's Validate() method (unfortunately in this case :) ).
The easiest solution would be to construct just one instance of BaseService (along with the authenticator), then re-use that instance for each outbound request.

**Comment by padamstx** [comment]
Closing this because I think we have a solution.  If you have additional questions or problems, feel free to re-open.
