### ISSUE TITLE
Update the RedactSecrets Regex to Support Satellite Storage Template Secret Parameter Names

### ISSUE THREAD

**Issue by aayushsss1** [IBM/go-sdk-core#190]
Due to current developments in providing Terraform support for satellite storage configurations, the names of secret parameters within storage templates that are used in the creation of these configurations are visible in the Terraform Logs and are required to be **redacted**.  These secret parameters of storage templates vary in name depending on the provider (Eg : RedHat, AWS, Azure etc) and are as follows -

**Redhat** 
ibm-cos-access-key
ibm-cos-secret-key
iam-api-key
kms-root-key
kms-api-key

**AWS** 
aws-access-key
aws-secret-access-key

**Azure** 
tenantId
subscriptionId
aadClientId
aadClientSecret

**Google**  
project_id
private_key_id
private_key
client_email
client_id
auth_uri
token_uri
auth_provider_x509_cert_url
client_x509_cert_url

**IBM** 
primary-gui-api-user
primary-gui-api-password
owning-gui-api-user
owning-gui-api-password
g2_api_key

**NetApp**
username
password

**VMware**
vcenter-username
vcenter-password
thumbprint

A possible solution would be to add the following keywords to the existing regex -

key, secret, thumbprint, auth, project_id, client_id, client_email, tenantId, subscriptionId, aadClientId, aadClientSecret, auth_uri, token_uri, auth_provider_x509_cert_url, client_x509_cert_url

**Comment by padamstx** [comment]
PR: https://github.com/IBM/go-sdk-core/pull/191
