### ISSUE TITLE
latest release (0.8.0) breaks watson-developer-cloud/go-sdk

### ISSUE THREAD

**Issue by ytwig** [IBM/go-sdk-core#24]
The latest release changes the core.ServiceOptions in a way it is not compatible with the go-sdk.
Since the go-sdk is grabbing the latest go-sdk-core, it is unable to compile.

Cross posting this here and on the go-sdk repos for visibility.

**Comment by ehdsouza** [comment]
This should be resolved as we have the core specified: https://github.com/watson-developer-cloud/go-sdk/blob/master/Gopkg.toml#L28
